name: Compile LaTeX document

on:
  push:
    branches:
      - 'main/**'
    path:
      - ['**.tex','**.cls','**.sty']

jobs:
  Build_LaTeX:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        latexmk_use_xelatex: true
        root_file: main.tex
    
    - name: Make Artifact
      run: |
        mkdir Artifact
        cp main.pdf Artifact/
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: Artifact
